force-app/main/default/objects/Contract_Line_Item__c/Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Contract Line Item</label>
    <nameField>
        <displayFormat>CLI-{0000000}</displayFormat>
        <label>Contract Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Line_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Opportunity_Line_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Item_Id__c</fullName>
    <description>Id of the corresponding OLI to be synced to CLI. Backend field, used in Triggers.</description>
    <label>Opportunity Line Item Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContractLineItemTriggerHandlerTest.cls
@isTest
public with sharing class ContractLineItemTriggerHandlerTest {
    @testSetup static void dataSetup(){
        TestUtility.createTriggerSettings();
        Opportunity getOportunityObj = TestUtility.createOpportunity();
       
        OpportunityLineItem opportunityLineItemObj =  TestUtility.createOpportunityLineItem(getOportunityObj);

        Contract getcontractObj = TestUtility.createContract(getOportunityObj);

        Contract_Line_Item__c contractLineItemObj = new  Contract_Line_Item__c();           
        contractLineItemObj.Contract__c = getcontractObj.Id;
        contractLineItemObj.Opportunity_Line_Item_Id__c = opportunityLineItemObj.Id;

        insert contractLineItemObj;


    }
    @isTest
    static void testUpdateContractLineItemTrigger(){
        Contract_Line_Item__c contractLineItemObj =[SELECT Id FROM Contract_Line_Item__c LIMIT 1];
        System.assertNotEquals(contractLineItemObj, null);
        update contractLineItemObj;

    }
    @isTest
    static void testDeleteContractLineItemTrigger(){
        Contract_Line_Item__c contractLineItemObj =[SELECT Id FROM Contract_Line_Item__c LIMIT 1];
        System.assertNotEquals(contractLineItemObj, null);
        delete contractLineItemObj;

    }
}