force-app/main/default/objects/Contract_Line_Item__c/Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Contract Line Item</label>
    <nameField>
        <displayFormat>CLI-{0000000}</displayFormat>
        <label>Contract Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Line_Item__c/fields/Opportunity_Line_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Item_Id__c</fullName>
    <description>Id of the corresponding OLI to be synced to CLI. Backend field, used in Triggers.</description>
    <label>Opportunity Line Item Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>Rate_Type__c</fullName>
    <label>Rate Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerSettings__c/TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to disable trigger on a specified object</description>
    <label>TriggerSettings</label>
</CustomObject>

force-app/main/default/objects/TriggerSettings__c/fields/TriggerDisabled__c.field-meta.xml
<CustomField>
    <fullName>TriggerDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this field to disable trigger on specified object</description>
    <inlineHelpText>Check this field to disable trigger on specified object</inlineHelpText>
    <label>TriggerDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContractLineItemTriggerHandler.cls
public class ContractLineItemTriggerHandler implements TriggerHandlerInterface
{
    // Allows unit tests (or other code) to disable this trigger for the transaction
    public static Boolean TriggerDisabled = false;
 
    /*
        Checks to see if the trigger has been disabled either by custom setting
    */
    public Boolean IsDisabled()
    {
        System.debug('ContractLineItemTriggerHandler.IsDisabled executing');
        if (TriggerSettings__c.getInstance('Contract_Line_Item__c').TriggerDisabled__c){
            return true;
        } else {
            return TriggerDisabled;
        }
    }
 
    public void BeforeInsert(List<SObject> newItems) {}
     
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {}
 
    public void BeforeDelete(Map<Id, SObject> oldItems) {}
 
    public void AfterInsert(Map<Id, SObject> newItems) {

        createContractLineItemSchedule((Map<Id, Contract_Line_Item__c>) newItems);
        GenerateNewContractLineItemDiscount.checkIfItemIsDiscounted((Map<Id, Contract_Line_Item__c>) newItems);
    }
 
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        
        
    }
 
    public void AfterDelete(Map<Id, SObject> oldItems) {}
 
    public void AfterUndelete(Map<Id, SObject> oldItems) {}

    /**
    * @description  Create Contract Line Item Schedule after creating Contract Line Items
	*/
    private void createContractLineItemSchedule(Map<Id, Contract_Line_Item__c> newItems){
        
        Set<String> opportunityLineItemIds = new Set<String>();
        for(Contract_Line_Item__c  contractLineItemObj : newItems.values()){

            opportunityLineItemIds.add(contractLineItemObj.Opportunity_Line_Item_Id__c);
            

        }
        List<OpportunityLineItemSchedule> opportunityLineItemScheduleLIst  =[SELECT Id ,Revenue,  OpportunityLineItem.OpportunityId, OpportunityLineItemId,ScheduleDate, 
                                                                                OpportunityLineItem.UnitPrice,
                                                                                OpportunityLineItem.Rate_Type__c
                                                                                FROM OpportunityLineItemSchedule
                                                                                WHERE OpportunityLineItemId =: opportunityLineItemIds];
        OpportunityLineItemTriggerHandler.createContractLineItemSchedule(newItems.keySet(),opportunityLineItemScheduleLIst);
        
    }
}