force-app/main/default/objects/DeDupe_Record_Back_Up__c/DeDupe_Record_Back_Up__c.object-meta.xml
<CustomObject>
    <description>Object to hold backup records that have been lost via de duping and merge processes. Functions as a way of tracking which objects where merged and to which winners.</description>
    <label>DeDupe Record Back Up</label>
    <nameField>
        <displayFormat>BR-{0000000}</displayFormat>
        <label>Backup Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DeDupe Record Back Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Original_Object__c.field-meta.xml
<CustomField>
    <fullName>Original_Object__c</fullName>
    <description>Holds information of what object this back up was taken from</description>
    <label>Original Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Original_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Record_Id__c</fullName>
    <description>Id of the record in the org before merge and de dupe</description>
    <label>Original Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Winner_ID__c.field-meta.xml
<CustomField>
    <fullName>Winner_ID__c</fullName>
    <description>Holds the Id of the &apos;Winner&apos; Record ID in the org that this loser record was merged into. ONLY POPULATED ON LOSER RECORDS</description>
    <label>Winner ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Winner_or_Loser__c.field-meta.xml
<CustomField>
    <fullName>Winner_or_Loser__c</fullName>
    <description>Value to represent if this was a &apos;loser&apos; or &apos;winner&apos; during a merge</description>
    <label>Winner or Loser</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Loser</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReparentChildrenPostDedupeBatched.cls
global class ReparentChildrenPostDedupeBatched implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String originalOBJ = 'Account';
        String loserTag = 'Loser';
        String query = 'SELECT Id,Original_Record_Id__c, Winner_ID__c FROM DeDupe_Record_Back_Up__c WHERE Original_Object__c = :originalOBJ AND Winner_or_Loser__c = :loserTag';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<DeDupe_Record_Back_Up__c> allLoserAccountBackupRecords) {
        
        Map<String,String> loserAccountOriginalIdToWinnerId = new Map<String,String>();
        List<String> loserAccountOriginalIds = new List<String>();
        
        for(DeDupe_Record_Back_Up__c loserAccount : allLoserAccountBackupRecords){
            loserAccountOriginalIdToWinnerId.put(loserAccount.Original_Record_Id__c, loserAccount.Winner_ID__c);
            loserAccountOriginalIds.add(loserAccount.Original_Record_Id__c);
        }
        //ReparentChildrenPostDedupe.addReparentedOppsandContactsToBackup(loserAccountOriginalIds,allLoserAccountBackupRecords);
        //ReparentChildrenPostDedupe.reparentOpportunities(allLoserAccountBackupRecords,loserAccountOriginalIdToWinnerId,loserAccountOriginalIds);
        //ReparentChildrenPostDedupe.reparentContacts(allLoserAccountBackupRecords,loserAccountOriginalIdToWinnerId,loserAccountOriginalIds);
        ReparentChildrenPostDedupe.reparentContracts(allLoserAccountBackupRecords,loserAccountOriginalIdToWinnerId,loserAccountOriginalIds);
    }
    
    global void finish(Database.BatchableContext BC) {
        system.debug('BATCH FINISHED');
    }
    
}