force-app/main/default/objects/DeDupe_Record_Back_Up__c/DeDupe_Record_Back_Up__c.object-meta.xml
<CustomObject>
    <description>Object to hold backup records that have been lost via de duping and merge processes. Functions as a way of tracking which objects where merged and to which winners.</description>
    <label>DeDupe Record Back Up</label>
    <nameField>
        <displayFormat>BR-{0000000}</displayFormat>
        <label>Backup Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DeDupe Record Back Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Original_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Record_Id__c</fullName>
    <description>Id of the record in the org before merge and de dupe</description>
    <label>Original Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Re_Parented_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Re_Parented_Contacts__c</fullName>
    <description>Record Ids of reparented Contacts on loser records. ONLY POPULATED ON LOSER RECORD</description>
    <label>Re-Parented Contacts</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Re_Parented_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Re_Parented_Opportunities__c</fullName>
    <description>Holds the Ids of Opportunities that were reparented on a loser record. ONLY POPULATED ON LOSER RECORD</description>
    <label>Re-Parented Opportunities</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ReparentChildrenPostDedupe.cls
public class ReparentChildrenPostDedupe {
    
    public static void reparentOpportunities(List<DeDupe_Record_Back_Up__c> allLoserAccountBackupRecords,Map<String,String> loserAccountOriginalIdToWinnerId,
                                             List<String> loserAccountOriginalIds)
    {
        List<Opportunity> opportunitiesToBeReparented = new List<Opportunity>();
        
        
        for(opportunity o : [SELECT id,AccountId,Name FROM Opportunity 
                             WHERE AccountId IN :loserAccountOriginalIds])
        {
            o.AccountId = loserAccountOriginalIdToWinnerId.get(o.AccountId);
            opportunitiesToBeReparented.add(o);
        }
        
        if(!opportunitiesToBeReparented.isEmpty()){
            update opportunitiesToBeReparented;
        }
    }
    
    public static void reparentContacts(List<DeDupe_Record_Back_Up__c> allLoserAccountBackupRecords,Map<String,String> loserAccountOriginalIdToWinnerId,
                                        List<String> loserAccountOriginalIds)
    {
        List<Contact> contactsToBeReparented = new List<Contact>();
        
        for(contact c : [SELECT id,AccountId FROM Contact 
                         WHERE AccountId IN :loserAccountOriginalIds])
        {
            c.AccountId = loserAccountOriginalIdToWinnerId.get(c.AccountId);
            contactsToBeReparented.add(c);
        }
        
        if(!contactsToBeReparented.isEmpty()){
            update contactsToBeReparented;
        }
        removeHistoricContactAccountRelationships(contactsToBeReparented,loserAccountOriginalIds);
        
    }
    
    public static void removeHistoricContactAccountRelationships(List<Contact> contactsToBeReparented,List<String> loserAccountOriginalIds)
    {
        List<String> reparentedContactIds = new List<String>();
        
        for(Contact c : contactsToBeReparented){
            reparentedContactIds.add(c.id);
        }
        
        List<AccountContactRelation> LoserAccountContactRelationships = [SELECT id 
                                                                         FROM AccountContactRelation 
                                                                         WHERE AccountId IN :loserAccountOriginalIds
                                                                         AND ContactId IN :reparentedContactIds];
        if(!LoserAccountContactRelationships.isEmpty()){
            delete LoserAccountContactRelationships;
        }
    }
    
    public static void reparentContracts(List<DeDupe_Record_Back_Up__c> allLoserAccountBackupRecords,Map<String,String> loserAccountOriginalIdToWinnerId,
                                         List<String> loserAccountOriginalIds)
    {
        List<Contract> contractsToBeReparented = new List<Contract>();
        
        for(Contract c : [SELECT id,AccountId FROM Contract 
                          WHERE AccountId IN :loserAccountOriginalIds])
        {
            c.AccountId = loserAccountOriginalIdToWinnerId.get(c.AccountId);
            contractsToBeReparented.add(c);
        }
        
        if(!contractsToBeReparented.isEmpty()){
            update contractsToBeReparented;
        }
        
    }
    
    public static void addReparentedOppsandContactsToBackup(List<String> loserAccountOriginalIds,List<DeDupe_Record_Back_Up__c> allLoserAccountBackupRecords){
        
        List<DeDupe_Record_Back_Up__c> bRToUpdate = new List<DeDupe_Record_Back_Up__c>();
        List<Opportunity> OppsFromLoserAccounts = [SELECT id,Name,AccountId FROM Opportunity WHERE AccountId IN :loserAccountOriginalIds];
        List<Contact> ContactFromLoserAccounts = [SELECT id,Name,AccountId FROM Contact WHERE AccountId IN :loserAccountOriginalIds];
        Map<String, List<String>> LoserAccountIdToOpportunityNames = new Map<String,List<String>>();
        Map<String, List<String>> LoserAccountIdToContactNames = new Map<String,List<String>>();
        
        for(String s : loserAccountOriginalIds){
            List<String> oppNames = new List<String>();
            for(Opportunity o : OppsFromLoserAccounts){
                if(o.AccountId == s){
                    oppNames.add(o.Name);
                }
            }
            LoserAccountIdToOpportunityNames.put(s, oppNames);
        }
        
        for(String s : loserAccountOriginalIds){
            List<String> contNames = new List<String>();
            for(Contact c : ContactFromLoserAccounts){
                if(c.AccountId == s){
                    contNames.add(c.Name);
                }
            }
            LoserAccountIdToContactNames.put(s, contNames);
        }
        
        for(DeDupe_Record_Back_Up__c dBR : allLoserAccountBackupRecords){
            
            dBR.Re_Parented_Opportunities__c = string.join(LoserAccountIdToOpportunityNames.get(dBR.Original_Record_Id__c), ', ');
            dBR.Re_Parented_Contacts__c = string.join(LoserAccountIdToContactNames.get(dBR.Original_Record_Id__c), ', ');
            bRToUpdate.add(dBR);
        }
        
        if(!bRToUpdate.isEmpty()){
            update bRToUpdate;
        }
        
    }
    
    
}