force-app/main/default/objects/DeDupe_Record_Back_Up__c/DeDupe_Record_Back_Up__c.object-meta.xml
<CustomObject>
    <description>Object to hold backup records that have been lost via de duping and merge processes. Functions as a way of tracking which objects where merged and to which winners.</description>
    <label>DeDupe Record Back Up</label>
    <nameField>
        <displayFormat>BR-{0000000}</displayFormat>
        <label>Backup Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DeDupe Record Back Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/De_Dupe_Key_Description__c.field-meta.xml
<CustomField>
    <fullName>De_Dupe_Key_Description__c</fullName>
    <description>Holds the description for how a record was isolated as a duplicate. (Matching Rule)</description>
    <label>De Dupe Key Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/De_Dupe_Key_Value__c.field-meta.xml
<CustomField>
    <fullName>De_Dupe_Key_Value__c</fullName>
    <description>Value of the de dupe key from the original record (e.g &quot;JohnSmithJsmith@gmail.com&quot; would be derived from a De dupe rule of FirstName + LastName + Email)</description>
    <label>De Dupe Key Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Original_Object__c.field-meta.xml
<CustomField>
    <fullName>Original_Object__c</fullName>
    <description>Holds information of what object this back up was taken from</description>
    <label>Original Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Original_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Record_Id__c</fullName>
    <description>Id of the record in the org before merge and de dupe</description>
    <label>Original Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Winner_ID__c.field-meta.xml
<CustomField>
    <fullName>Winner_ID__c</fullName>
    <description>Holds the Id of the &apos;Winner&apos; Record ID in the org that this loser record was merged into. ONLY POPULATED ON LOSER RECORDS</description>
    <label>Winner ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Winner_or_Loser__c.field-meta.xml
<CustomField>
    <fullName>Winner_or_Loser__c</fullName>
    <description>Value to represent if this was a &apos;loser&apos; or &apos;winner&apos; during a merge</description>
    <label>Winner or Loser</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Loser</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReparentChildrenPostDedupe_Test.cls
@isTest
public class ReparentChildrenPostDedupe_Test {
    
    @TestSetup
    static void setupData(){
        String sourceAccount = TestUtility.createAccount();
        Account sourceAccountObj = [SELECT id,Name FROM Account WHERE Id = :sourceAccount LIMIT 1];
        sourceAccountObj.Name = 'Source Account';
        update sourceAccountObj;
        
        String winnerAccount = TestUtility.createAccount();
        Account winnerAccountObj = [SELECT id,Name FROM Account WHERE Id = :winnerAccount LIMIT 1];
        winnerAccountObj.Name = 'winner Account';
        update winnerAccountObj;
        
        Campaign testCampaign = new Campaign();
        testCampaign.Name = 'Test Campaign';
        insert testCampaign;
        
        TestUtility.createTriggerSettings();
        Opportunity sourceOpportunity = TestUtility.createOpportunity();
        sourceOpportunity.AccountId = sourceAccount;
        update sourceOpportunity;
        
        Contact sourceContact = new Contact();
        sourceContact.FirstName = 'Test';
        sourceContact.LastName = 'Contact';
        sourceContact.Email = 'Test@test.com';
        sourceContact.AccountId = sourceAccount;
        insert sourceContact;
        
        DeDupe_Record_Back_Up__c winnerAccountBR = new DeDupe_Record_Back_Up__c();
        winnerAccountBR.De_Dupe_Key_Description__c = 'Billing Address';
        winnerAccountBR.De_Dupe_Key_Value__c = '123TestLane';
        winnerAccountBR.Original_Object__c = 'Account';
        winnerAccountBR.Original_Record_Id__c = winnerAccount;
        winnerAccountBR.Winner_ID__c = 'NA';
        winnerAccountBR.Winner_or_Loser__c = 'Winner';
        insert winnerAccountBR;
        
        DeDupe_Record_Back_Up__c loserAccountBR = new DeDupe_Record_Back_Up__c();
        loserAccountBR.De_Dupe_Key_Description__c = 'Billing Address';
        loserAccountBR.De_Dupe_Key_Value__c = '123TestLane';
        loserAccountBR.Original_Object__c = 'Account';
        loserAccountBR.Original_Record_Id__c = sourceAccount;
        loserAccountBR.Winner_ID__c = winnerAccount;
        loserAccountBR.Winner_or_Loser__c = 'Loser';
        insert loserAccountBR;
        
        Contract testContract = new Contract();
        testContract.AccountId = sourceAccount;
        testContract.StartDate = system.today();
        testContract.ContractTerm = 1;
        insert testContract;
    }
    
    @isTest
    static void checkOpportunityisReparented(){
        
        Account winnerAccount = [SELECT Id From Account WHERE Name = 'winner Account'];
        
        DeDupe_Record_Back_Up__c loserAccountBR = [SELECT Original_Record_Id__c, Winner_ID__c 
                                                   FROM DeDupe_Record_Back_Up__c 
                                                   WHERE Winner_or_Loser__c = 'Loser'
                                                   LIMIT 1];
        
        Opportunity beforeReparent = [SELECT id, AccountId FROM Opportunity LIMIT 1];
        system.assert(beforeReparent.AccountId == loserAccountBR.Original_Record_Id__c);
        
        Test.startTest();
        ReparentChildrenPostDedupeBatched ReparentChildrenPostDedupeBatched = new ReparentChildrenPostDedupeBatched(); 
        Id batchId = Database.executeBatch(ReparentChildrenPostDedupeBatched,100); 
        Test.stopTest();
        Opportunity afterReparent = [SELECT id, AccountId FROM Opportunity LIMIT 1];
        system.assertEquals(winnerAccount.id, afterReparent.AccountId);
        
    }
    
    @isTest
    static void checkContactisReparented(){
        
        Account winnerAccount = [SELECT Id From Account WHERE Name = 'winner Account'];
        
        DeDupe_Record_Back_Up__c loserAccountBR = [SELECT Original_Record_Id__c, Winner_ID__c 
                                                   FROM DeDupe_Record_Back_Up__c 
                                                   WHERE Winner_or_Loser__c = 'Loser'
                                                   LIMIT 1];
        
        Contact beforeReparent = [SELECT id, AccountId FROM Contact LIMIT 1];
        system.assert(beforeReparent.AccountId == loserAccountBR.Original_Record_Id__c);
        AccountContactRelation relationShipBeforeReparent = [SELECT id,ContactId,AccountId FROM AccountContactRelation WHERE ContactId = :beforeReparent.id];
        system.assert(relationShipBeforeReparent.accountId == beforeReparent.AccountId);
        
        Test.startTest();
        ReparentChildrenPostDedupeBatched ReparentChildrenPostDedupeBatched = new ReparentChildrenPostDedupeBatched(); 
        Id batchId = Database.executeBatch(ReparentChildrenPostDedupeBatched,100);
        Test.stopTest();
        Contact afterReparent = [SELECT id, AccountId FROM Contact LIMIT 1];
        system.assertEquals(winnerAccount.id, afterReparent.AccountId);
        AccountContactRelation relationShipAfterReparent = [SELECT id,ContactId,AccountId FROM AccountContactRelation WHERE ContactId = :afterReparent.id];
        system.assert(relationShipAfterReparent.accountId == afterReparent.AccountId);
        
    }
    
    
    @isTest
    static void checkContractisReparented(){
        
        Account winnerAccount = [SELECT Id From Account WHERE Name = 'winner Account'];
        
        DeDupe_Record_Back_Up__c loserAccountBR = [SELECT Original_Record_Id__c, Winner_ID__c 
                                                   FROM DeDupe_Record_Back_Up__c 
                                                   WHERE Winner_or_Loser__c = 'Loser'
                                                   LIMIT 1];
        
        Contract beforeReparent = [SELECT Id,AccountID FROM Contract LIMIT 1];
        system.assert(beforeReparent.AccountId == loserAccountBR.Original_Record_Id__c);
        
        Test.startTest();
        ReparentChildrenPostDedupeBatched ReparentChildrenPostDedupeBatched = new ReparentChildrenPostDedupeBatched(); 
        Id batchId = Database.executeBatch(ReparentChildrenPostDedupeBatched,100);
        Test.stopTest();
        
        Contract afterReparent = [SELECT Id,AccountID FROM Contract LIMIT 1];
        system.assertEquals(winnerAccount.id, afterReparent.AccountId);
    }
    
}