force-app/main/default/objects/DeDupe_Record_Back_Up__c/DeDupe_Record_Back_Up__c.object-meta.xml
<CustomObject>
    <description>Object to hold backup records that have been lost via de duping and merge processes. Functions as a way of tracking which objects where merged and to which winners.</description>
    <label>DeDupe Record Back Up</label>
    <nameField>
        <displayFormat>BR-{0000000}</displayFormat>
        <label>Backup Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DeDupe Record Back Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/De_Dupe_Key_Description__c.field-meta.xml
<CustomField>
    <fullName>De_Dupe_Key_Description__c</fullName>
    <description>Holds the description for how a record was isolated as a duplicate. (Matching Rule)</description>
    <label>De Dupe Key Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/De_Dupe_Key_Value__c.field-meta.xml
<CustomField>
    <fullName>De_Dupe_Key_Value__c</fullName>
    <description>Value of the de dupe key from the original record (e.g &quot;JohnSmithJsmith@gmail.com&quot; would be derived from a De dupe rule of FirstName + LastName + Email)</description>
    <label>De Dupe Key Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Original_Object__c.field-meta.xml
<CustomField>
    <fullName>Original_Object__c</fullName>
    <description>Holds information of what object this back up was taken from</description>
    <label>Original Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Original_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Record_Id__c</fullName>
    <description>Id of the record in the org before merge and de dupe</description>
    <label>Original Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Re_Parented_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Re_Parented_Contacts__c</fullName>
    <description>Record Ids of reparented Contacts on loser records. ONLY POPULATED ON LOSER RECORD</description>
    <label>Re-Parented Contacts</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Re_Parented_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Re_Parented_Opportunities__c</fullName>
    <description>Holds the Ids of Opportunities that were reparented on a loser record. ONLY POPULATED ON LOSER RECORD</description>
    <label>Re-Parented Opportunities</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Winner_ID__c.field-meta.xml
<CustomField>
    <fullName>Winner_ID__c</fullName>
    <description>Holds the Id of the &apos;Winner&apos; Record ID in the org that this loser record was merged into. ONLY POPULATED ON LOSER RECORDS</description>
    <label>Winner ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Winner_or_Loser__c.field-meta.xml
<CustomField>
    <fullName>Winner_or_Loser__c</fullName>
    <description>Value to represent if this was a &apos;loser&apos; or &apos;winner&apos; during a merge</description>
    <label>Winner or Loser</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Loser</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TriggerSettings__c/TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to disable trigger on a specified object</description>
    <label>TriggerSettings</label>
</CustomObject>

force-app/main/default/objects/TriggerSettings__c/fields/TriggerDisabled__c.field-meta.xml
<CustomField>
    <fullName>TriggerDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this field to disable trigger on specified object</description>
    <inlineHelpText>Check this field to disable trigger on specified object</inlineHelpText>
    <label>TriggerDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UnMergeFromBackups_Test.cls
@isTest
public class UnMergeFromBackups_Test {
    
    @TestSetup
    public static void setupData(){
        
        List<TriggerSettings__c> triggerSettingsList = new List<TriggerSettings__c>();
        TriggerSettings__c triggerSettingsObj = new TriggerSettings__c(Name = 'Opportunity', TriggerDisabled__c = false);
        triggerSettingsList.add(triggerSettingsObj);
        insert triggerSettingsList;
        
        //Create Accounts Winner and Loser
        List<Account> aToInsert = new List<Account>();        
        Account lAccount = new Account();
        lAccount.Name = 'LOSER ACCOUNT';
        lAccount.BillingStreet = '3022  Strother Street';
        lAccount.BillingCity = 'Into';
        lAccount.BillingState = 'Alabama';
        lAccount.BillingPostalCode = '35222';
        lAccount.BillingCountry = 'US';
        aToInsert.add(lAccount);
        
        Account wAccount = new Account();
        wAccount.Name = 'WINNER ACCOUNT';
        wAccount.BillingStreet = '3022  Strother Street';
        wAccount.BillingCity = 'Into';
        wAccount.BillingState = 'Alabama';
        wAccount.BillingPostalCode = '35222';
        wAccount.BillingCountry = 'US';
        aToInsert.add(wAccount);
        
        insert aToInsert;
        
        //Create Contacts under Winner
        List<Contact> cToInsert = new List<Contact>();
        Contact c1 = new Contact();
        c1.FirstName = 'Contact';
        c1.LastName = '1';
        c1.AccountId = wAccount.Id;
        cToInsert.add(c1);
        
        Contact c2 = new Contact();
        c2.FirstName = 'Contact';
        c2.LastName = '2';
        c2.AccountId = wAccount.Id;
        cToInsert.add(c2);
        
        Contact c3 = new Contact();
        c3.FirstName = 'Contact';
        c3.LastName = '3';
        c3.AccountId = wAccount.Id;
        cToInsert.add(c3);
        
        insert cToInsert;
        
        //Create Opportunities under Winner
        List<Opportunity> oToInsert = new List<Opportunity>();
        
        Opportunity o1 = new Opportunity();
        o1.Name = 'Opportunity-1';
        o1.AccountId  = wAccount.Id;
        o1.StageName = 'Proposal';
        o1.CloseDate = System.today();
        oToInsert.add(o1);
        
        Opportunity o2 = new Opportunity();
        o2.Name = 'Opportunity-2';
        o2.AccountId  = wAccount.Id;
        o2.StageName = 'Proposal';
        o2.CloseDate = System.today();
        oToInsert.add(o2);
        
        Opportunity o3 = new Opportunity();
        o3.Name = 'Opportunity-3';
        o3.AccountId  = wAccount.Id;
        o3.StageName = 'Proposal';
        o3.CloseDate = System.today();
        oToInsert.add(o3);
        
        insert oToInsert;
        
        //Create DeDupe Backup Records Winner and Loser
        List<DeDupe_Record_Back_Up__c> dbrToInsert = new List<DeDupe_Record_Back_Up__c>();
        DeDupe_Record_Back_Up__c lDbr = new DeDupe_Record_Back_Up__c();
        lDbr.Original_Object__c = 'Account';
        lDbr.Winner_or_Loser__c = 'Loser';
        lDbr.De_Dupe_Key_Description__c = 'Name';
        lDbr.De_Dupe_Key_Value__c = 'Test';
        //lDbr.Re_Parented_Contacts__c = c1.Name + ', ' + c2.Name + ', ' + c3.Name;
        //system.debug('lDbr.Re_Parented_Contacts__c ==> ' + lDbr.Re_Parented_Contacts__c);
        lDbr.Re_Parented_Contacts__c = c1.FirstName+' '+c1.LastName+', '+c2.FirstName+' '+c2.LastName+', '+c3.FirstName+' '+c3.LastName;
        system.debug('lDbr.Re_Parented_Contacts__c ==> ' + lDbr.Re_Parented_Contacts__c);
        lDbr.Re_Parented_Opportunities__c = o1.Name + ', ' + o2.Name + ', ' + o3.Name;
        lDbr.Original_Record_Id__c = Id.valueOf(lAccount.Id);
        lDbr.Winner_ID__c = Id.valueOf(wAccount.Id);
        dbrToInsert.add(lDbr);
        
        DeDupe_Record_Back_Up__c wDbr = new DeDupe_Record_Back_Up__c();
        wDbr.Original_Object__c = 'Account';
        wDbr.Winner_or_Loser__c = 'Winner';
        wDbr.De_Dupe_Key_Description__c = 'Name';
        wDbr.De_Dupe_Key_Value__c = 'Test';
        wDbr.Re_Parented_Contacts__c = '';
        wDbr.Re_Parented_Opportunities__c = '';
        wDbr.Original_Record_Id__c = Id.valueOf(wAccount.Id);
        wDbr.Winner_ID__c = 'N/A';
        dbrToInsert.add(wDbr);
        
        insert dbrToInsert;
    }
    
    @IsTest
    public static void testOpportunityReparent(){
        
        List<Opportunity> oppsBeforeReParent = [SELECT id, Account.Name, AccountId FROM Opportunity];
        Assert.areEqual('WINNER ACCOUNT', oppsBeforeReParent[0].Account.Name);
        Assert.areEqual('WINNER ACCOUNT', oppsBeforeReParent[1].Account.Name);
        Assert.areEqual('WINNER ACCOUNT', oppsBeforeReParent[2].Account.Name);
        
        Test.startTest();
        //UnMergeFromBackups.reverseReparentingOpportunities();
        UnMergeFromBackupsBatched batch = new UnMergeFromBackupsBatched(); 
        Id batchId = Database.executeBatch(batch,100);
        Test.stopTest();
        
        List<Opportunity> oppsAfterReParent = [SELECT id, Account.Name, AccountId FROM Opportunity];
        //Assert.areEqual('LOSER ACCOUNT', oppsAfterReParent[0].Account.Name);
        //Assert.areEqual('LOSER ACCOUNT', oppsAfterReParent[1].Account.Name);
        //Assert.areEqual('LOSER ACCOUNT', oppsAfterReParent[2].Account.Name);

        
        
        
    }
    
    @IsTest
    public static void testContactReparent(){
        List<Contact> contsBeforeReParent = [SELECT id, Account.Name, AccountId FROM Contact];
        Assert.areEqual('WINNER ACCOUNT', contsBeforeReParent[0].Account.Name);
        Assert.areEqual('WINNER ACCOUNT', contsBeforeReParent[1].Account.Name);
        Assert.areEqual('WINNER ACCOUNT', contsBeforeReParent[2].Account.Name);
        
        Test.startTest();
        //UnMergeFromBackups.reverseReparentingContacts();
        UnMergeFromBackupsBatched batch = new UnMergeFromBackupsBatched(); 
        Id batchId = Database.executeBatch(batch,100);
        Test.stopTest();
        
        List<Contact> contsAfterReParent = [SELECT id, Account.Name, AccountId FROM Contact];
        Assert.areEqual('LOSER ACCOUNT', contsAfterReParent[0].Account.Name);
        Assert.areEqual('LOSER ACCOUNT', contsAfterReParent[1].Account.Name);
        Assert.areEqual('LOSER ACCOUNT', contsAfterReParent[2].Account.Name);
        
    }
   
    @isTest
    public static void checkNonReparentedOpps(){
        Account a = [SELECT Id, Name FROM Account WHERE Name = 'WINNER ACCOUNT'];
        Opportunity o = new Opportunity();
        o.Name = 'DO NOT REPARENT';
        o.AccountId  = a.Id;
        o.StageName = 'Proposal';
        o.CloseDate = System.today();
        insert o;
        
        List<Opportunity> oppsBeforeReParent = [SELECT id, Account.Name,Name, AccountId FROM Opportunity];
        for(Opportunity op : oppsBeforeReParent){
            if(op.Name != 'DO NOT REPARENT'){
              Assert.areEqual('WINNER ACCOUNT', op.Account.Name);  
            }else{
              Assert.areEqual('WINNER ACCOUNT', op.Account.Name); 
            }
        }
        
        Test.startTest();
        //UnMergeFromBackups.reverseReparentingOpportunities();
        UnMergeFromBackupsBatched batch = new UnMergeFromBackupsBatched(); 
        Id batchId = Database.executeBatch(batch,100);
        Test.stopTest();
        
        List<Opportunity> oppsAfterReParent = [SELECT id, Account.Name,Name, AccountId FROM Opportunity];
        for(Opportunity op : oppsAfterReParent){
            if(op.Name != 'DO NOT REPARENT'){
              //Assert.areEqual('LOSER ACCOUNT', op.Account.Name);  
            }else{
              //Assert.areEqual('WINNER ACCOUNT', op.Account.Name); 
            }
        }    
    }
    
    @isTest
    public static void checkNonReparentedContacts(){
        
        Account a = [SELECT Id, Name FROM Account WHERE Name = 'WINNER ACCOUNT'];
        Contact c = new Contact();
        c.FirstName = 'DONOT';
        c.LastName = 'Reparent';
        c.AccountId  = a.Id;
        insert c;
        
        List<Contact> contsBeforeReParent = [SELECT id, Account.Name,Name,FirstName,LastName,AccountId FROM Contact];
        for(Contact co : contsBeforeReParent){
            if(co.FirstName + ' ' + co.LastName != 'DONOT REPARENT'){
              Assert.areEqual('WINNER ACCOUNT', co.Account.Name);  
            }else{
              Assert.areEqual('WINNER ACCOUNT', co.Account.Name); 
            }
        }
        
        Test.startTest();
        //UnMergeFromBackups.reverseReparentingContacts();
        UnMergeFromBackupsBatched batch = new UnMergeFromBackupsBatched(); 
        Id batchId = Database.executeBatch(batch,100);
        Test.stopTest();
        
        List<Contact> contAfterReParent = [SELECT id, Account.Name,Name,FirstName,LastName,AccountId FROM Contact];
        for(Contact co : contAfterReParent){
            if(co.FirstName + ' ' + co.LastName != 'DONOT REPARENT'){
              Assert.areEqual('LOSER ACCOUNT', co.Account.Name);  
            }else{
              Assert.areEqual('WINNER ACCOUNT', co.Account.Name); 
            }
        }
    }
}