force-app/main/default/objects/DeDupe_Record_Back_Up__c/DeDupe_Record_Back_Up__c.object-meta.xml
<CustomObject>
    <description>Object to hold backup records that have been lost via de duping and merge processes. Functions as a way of tracking which objects where merged and to which winners.</description>
    <label>DeDupe Record Back Up</label>
    <nameField>
        <displayFormat>BR-{0000000}</displayFormat>
        <label>Backup Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DeDupe Record Back Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Original_Object__c.field-meta.xml
<CustomField>
    <fullName>Original_Object__c</fullName>
    <description>Holds information of what object this back up was taken from</description>
    <label>Original Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Original_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Record_Id__c</fullName>
    <description>Id of the record in the org before merge and de dupe</description>
    <label>Original Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Re_Parented_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Re_Parented_Contacts__c</fullName>
    <description>Record Ids of reparented Contacts on loser records. ONLY POPULATED ON LOSER RECORD</description>
    <label>Re-Parented Contacts</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Re_Parented_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Re_Parented_Opportunities__c</fullName>
    <description>Holds the Ids of Opportunities that were reparented on a loser record. ONLY POPULATED ON LOSER RECORD</description>
    <label>Re-Parented Opportunities</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Winner_ID__c.field-meta.xml
<CustomField>
    <fullName>Winner_ID__c</fullName>
    <description>Holds the Id of the &apos;Winner&apos; Record ID in the org that this loser record was merged into. ONLY POPULATED ON LOSER RECORDS</description>
    <label>Winner ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Winner_or_Loser__c.field-meta.xml
<CustomField>
    <fullName>Winner_or_Loser__c</fullName>
    <description>Value to represent if this was a &apos;loser&apos; or &apos;winner&apos; during a merge</description>
    <label>Winner or Loser</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Loser</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UnMergeFromBackups.cls
public class UnMergeFromBackups {
    
    public static void reverseReparentingOpportunities(List<DeDupe_Record_Back_Up__c> allLoserBackups){
        List<Opportunity> toUpdate = new List<Opportunity>();
        
        Map<Id,List<String>> originalIdToListofOpportunityNames = new Map<Id,List<String>>();
        Map<Id,Id> WinnerIdToLoserId = new Map<Id,Id>();
        List<Id> WinnerIds = new List<Id>();
        
        for(DeDupe_Record_Back_Up__c dbr :allLoserBackups){
            if(dbr.Re_Parented_Opportunities__c != null){
            	List<String> lstOpportunityNames = dbr.Re_Parented_Opportunities__c.split(', ');
            	originalIdToListofOpportunityNames.put(Id.ValueOf(dbr.Original_Record_Id__c), lstOpportunityNames);
            	WinnerIds.add(Id.ValueOf(dbr.Winner_ID__c));
            	WinnerIdToLoserId.put(Id.ValueOf(dbr.Winner_ID__c),Id.ValueOf(dbr.Original_Record_Id__c));
            }
        }
        
        List<Opportunity> OppsWithWinnerId = [SELECT ID,Name,AccountId FROM Opportunity WHERE AccountId IN :WinnerIds];
        
        for(Opportunity o : OppsWithWinnerId){
            Id originalId = WinnerIdToLoserId.get(o.Accountid);
            List<String> oppList = originalIdToListofOpportunityNames.get(originalId);
            if(originalId != null){
                if(oppList.contains(o.Name)){
                    o.AccountId = originalId;
                    o.Was_Unmerged__c = True;
                    toUpdate.add(o);
                }
            }
        }
        
        if(!toUpdate.isEmpty()){
            update toUpdate;
        }
        
    }
    
    public static void reverseReparentingContacts(List<DeDupe_Record_Back_Up__c> allLoserBackups){
        List<Contact> toUpdate = new List<Contact>();
        
        Map<Id,List<String>> originalIdToListofContactNames = new Map<Id,List<String>>();
        Map<Id,Id> WinnerIdToLoserId = new Map<Id,Id>();
        List<Id> WinnerIds = new List<Id>();
        
        for(DeDupe_Record_Back_Up__c dbr :allLoserBackups){
            if(dbr.Re_Parented_Contacts__c != null){
            	List<String> lstContactNames = dbr.Re_Parented_Contacts__c.split(', ');
            	originalIdToListofContactNames.put(Id.ValueOf(dbr.Original_Record_Id__c), lstContactNames);
            	WinnerIds.add(Id.ValueOf(dbr.Winner_ID__c));
            	WinnerIdToLoserId.put(Id.ValueOf(dbr.Winner_ID__c),Id.ValueOf(dbr.Original_Record_Id__c));
            }
        }
        List<Contact> ContsWithWinnerId = [SELECT ID,Name,FirstName,LastName,AccountId FROM Contact WHERE AccountId IN :WinnerIds];
        
        for(Contact c : ContsWithWinnerId){
            Id originalId = WinnerIdToLoserId.get(c.AccountId);
            List<String> contList = originalIdToListofContactNames.get(originalId);
            if(originalId != null){
                if(contList.Contains(c.FirstName + ' ' + c.LastName)){
                    c.AccountId = originalId;
                    c.Was_Unmerged__c = True;
                    toUpdate.add(c);
                }
            }            
        }
        
        if(!toUpdate.isEmpty()){
            update toUpdate;
        }
        
    }
    
    /*
public static List<DeDupe_Record_Back_Up__c> getLoserBackupsUtil(){
List<DeDupe_Record_Back_Up__c> allLoserBackups = [SELECT ID, Winner_ID__c, Original_Record_Id__c, Original_Object__c, Re_Parented_Opportunities__c,Re_Parented_Contacts__c
FROM DeDupe_Record_Back_Up__c
WHERE Winner_or_Loser__c = 'Loser' AND Original_Object__c = 'Account']; 
return allLoserBackups;
}
*/
    
}