force-app/main/default/objects/DeDupe_Record_Back_Up__c/DeDupe_Record_Back_Up__c.object-meta.xml
<CustomObject>
    <description>Object to hold backup records that have been lost via de duping and merge processes. Functions as a way of tracking which objects where merged and to which winners.</description>
    <label>DeDupe Record Back Up</label>
    <nameField>
        <displayFormat>BR-{0000000}</displayFormat>
        <label>Backup Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DeDupe Record Back Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Original_Object__c.field-meta.xml
<CustomField>
    <fullName>Original_Object__c</fullName>
    <description>Holds information of what object this back up was taken from</description>
    <label>Original Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Original_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Record_Id__c</fullName>
    <description>Id of the record in the org before merge and de dupe</description>
    <label>Original Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Re_Parented_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Re_Parented_Contacts__c</fullName>
    <description>Record Ids of reparented Contacts on loser records. ONLY POPULATED ON LOSER RECORD</description>
    <label>Re-Parented Contacts</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Re_Parented_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Re_Parented_Opportunities__c</fullName>
    <description>Holds the Ids of Opportunities that were reparented on a loser record. ONLY POPULATED ON LOSER RECORD</description>
    <label>Re-Parented Opportunities</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Winner_ID__c.field-meta.xml
<CustomField>
    <fullName>Winner_ID__c</fullName>
    <description>Holds the Id of the &apos;Winner&apos; Record ID in the org that this loser record was merged into. ONLY POPULATED ON LOSER RECORDS</description>
    <label>Winner ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Winner_or_Loser__c.field-meta.xml
<CustomField>
    <fullName>Winner_or_Loser__c</fullName>
    <description>Value to represent if this was a &apos;loser&apos; or &apos;winner&apos; during a merge</description>
    <label>Winner or Loser</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Loser</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UnMergeFromBackupsBatched.cls
global class UnMergeFromBackupsBatched implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String originalOBJ = 'Account';
        String loserTag = 'Loser';
        String querySelect = 'SELECT ID, Winner_ID__c, Original_Record_Id__c, Original_Object__c, Re_Parented_Opportunities__c,Re_Parented_Contacts__c ';
        String queryFrom = 'FROM DeDupe_Record_Back_Up__c ';
        String queryWhere = 'WHERE Original_Object__c = :originalOBJ AND Winner_or_Loser__c = :loserTag AND UnMerged__c = False';
        String query = querySelect+queryFrom+queryWhere;
        return Database.getQueryLocator(query);
    }    
    
    global void execute(Database.BatchableContext BC, List<DeDupe_Record_Back_Up__c> allLoserAccountBackupRecords) {
        try{
        	UnMergeFromBackups.reverseReparentingContacts(allLoserAccountBackupRecords);
        }catch(Exception e){
            system.debug('reverseReparentingContacts');
            system.debug(e.getCause());
            system.debug(e.getLineNumber());
            system.debug(e.getMessage());
            system.debug(e.getTypeName());
        }
        
        try{
        	UnMergeFromBackups.reverseReparentingOpportunities(allLoserAccountBackupRecords);
        }catch(Exception e){
            system.debug('reverseReparentingOpportunities');
            system.debug(e.getCause());
            system.debug(e.getLineNumber());
            system.debug(e.getMessage());
            system.debug(e.getTypeName());
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        system.debug('Batch Complete!');
    }
}