force-app/main/default/objects/DeDupe_Record_Back_Up__c/DeDupe_Record_Back_Up__c.object-meta.xml
<CustomObject>
    <description>Object to hold backup records that have been lost via de duping and merge processes. Functions as a way of tracking which objects where merged and to which winners.</description>
    <label>DeDupe Record Back Up</label>
    <nameField>
        <displayFormat>BR-{0000000}</displayFormat>
        <label>Backup Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DeDupe Record Back Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/De_Dupe_Key_Description__c.field-meta.xml
<CustomField>
    <fullName>De_Dupe_Key_Description__c</fullName>
    <description>Holds the description for how a record was isolated as a duplicate. (Matching Rule)</description>
    <label>De Dupe Key Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/De_Dupe_Key_Value__c.field-meta.xml
<CustomField>
    <fullName>De_Dupe_Key_Value__c</fullName>
    <description>Value of the de dupe key from the original record (e.g &quot;JohnSmithJsmith@gmail.com&quot; would be derived from a De dupe rule of FirstName + LastName + Email)</description>
    <label>De Dupe Key Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Original_Object__c.field-meta.xml
<CustomField>
    <fullName>Original_Object__c</fullName>
    <description>Holds information of what object this back up was taken from</description>
    <label>Original Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Original_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Record_Id__c</fullName>
    <description>Id of the record in the org before merge and de dupe</description>
    <label>Original Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Winner_ID__c.field-meta.xml
<CustomField>
    <fullName>Winner_ID__c</fullName>
    <description>Holds the Id of the &apos;Winner&apos; Record ID in the org that this loser record was merged into. ONLY POPULATED ON LOSER RECORDS</description>
    <label>Winner ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Winner_or_Loser__c.field-meta.xml
<CustomField>
    <fullName>Winner_or_Loser__c</fullName>
    <description>Value to represent if this was a &apos;loser&apos; or &apos;winner&apos; during a merge</description>
    <label>Winner or Loser</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Loser</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WinnerIdTaggingForDeDupe_Test.cls
@isTest
public class WinnerIdTaggingForDeDupe_Test {
    
    @TestSetup
    static void setupData(){
        
        List<DeDupe_Record_Back_Up__c> backUpRecords = new List<DeDupe_Record_Back_Up__c>();
        
        DeDupe_Record_Back_Up__c br1Winner = new DeDupe_Record_Back_Up__c();
        br1Winner.De_Dupe_Key_Description__c = 'First Name + Last Name + Email';
        br1Winner.De_Dupe_Key_Value__c = 'TestNameTest.Name@gmail.com';
        br1Winner.Original_Object__c = 'Contact';
        br1Winner.Original_Record_Id__c = 'WinnerId1234567890';
        br1Winner.Winner_ID__c = 'NA';
        br1Winner.Winner_or_Loser__c = 'Winner';
        backUpRecords.add(br1Winner);
        
        DeDupe_Record_Back_Up__c br1Loser = new DeDupe_Record_Back_Up__c();
        br1Loser.De_Dupe_Key_Description__c = 'First Name + Last Name + Email';
        br1Loser.De_Dupe_Key_Value__c = 'TestNameTest.Name@gmail.com';
        br1Loser.Original_Object__c = 'Contact';
        br1Loser.Original_Record_Id__c = 'LoserId1234567890';
        br1Loser.Winner_or_Loser__c = 'Loser';
        backUpRecords.add(br1Loser);
        
        insert backUpRecords;
        
    }
    
    @isTest
    static void checkLosergetsWinnerId(){
        
        List<DeDupe_Record_Back_Up__c> beforeWinnerIdTagging = [Select Id, Winner_ID__c,Winner_or_Loser__c 
                                                                FROM DeDupe_Record_Back_Up__c
                                                                WHERE Winner_or_Loser__c = 'Loser'];
        
        System.assert(beforeWinnerIdTagging[0].Winner_ID__c == Null);
        
        Test.startTest();
        WinnerIdTaggingForDeDupe.setWinnerIds();
        Test.stopTest();
        
        List<DeDupe_Record_Back_Up__c> afterWinnerIdTagging = [Select Id, Winner_ID__c,Winner_or_Loser__c 
                                                               FROM DeDupe_Record_Back_Up__c
                                                               WHERE Winner_or_Loser__c = 'Loser'];
        
        System.assert(afterWinnerIdTagging[0].Winner_ID__c == 'WinnerId1234567890');
        
    }
    
    @isTest
    static void checkWinnerDoesntGetId(){
        
        List<DeDupe_Record_Back_Up__c> beforeWinnerIdTagging = [Select Id, Winner_ID__c,Winner_or_Loser__c 
                                                                FROM DeDupe_Record_Back_Up__c
                                                                WHERE Winner_or_Loser__c = 'Winner'];
        
        System.assert(beforeWinnerIdTagging[0].Winner_ID__c == 'NA');
        
        Test.startTest();
        WinnerIdTaggingForDeDupe.setWinnerIds();
        Test.stopTest();
        
        List<DeDupe_Record_Back_Up__c> afterWinnerIdTagging = [Select Id, Winner_ID__c,Winner_or_Loser__c 
                                                               FROM DeDupe_Record_Back_Up__c
                                                               WHERE Winner_or_Loser__c = 'Winner'];
        
        System.assert(afterWinnerIdTagging[0].Winner_ID__c == 'NA');
        
    }
    
}