force-app/main/default/objects/DeDupe_Record_Back_Up__c/DeDupe_Record_Back_Up__c.object-meta.xml
<CustomObject>
    <description>Object to hold backup records that have been lost via de duping and merge processes. Functions as a way of tracking which objects where merged and to which winners.</description>
    <label>DeDupe Record Back Up</label>
    <nameField>
        <displayFormat>BR-{0000000}</displayFormat>
        <label>Backup Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DeDupe Record Back Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/De_Dupe_Key_Value__c.field-meta.xml
<CustomField>
    <fullName>De_Dupe_Key_Value__c</fullName>
    <description>Value of the de dupe key from the original record (e.g &quot;JohnSmithJsmith@gmail.com&quot; would be derived from a De dupe rule of FirstName + LastName + Email)</description>
    <label>De Dupe Key Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Original_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Record_Id__c</fullName>
    <description>Id of the record in the org before merge and de dupe</description>
    <label>Original Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Winner_ID__c.field-meta.xml
<CustomField>
    <fullName>Winner_ID__c</fullName>
    <description>Holds the Id of the &apos;Winner&apos; Record ID in the org that this loser record was merged into. ONLY POPULATED ON LOSER RECORDS</description>
    <label>Winner ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeDupe_Record_Back_Up__c/fields/Winner_or_Loser__c.field-meta.xml
<CustomField>
    <fullName>Winner_or_Loser__c</fullName>
    <description>Value to represent if this was a &apos;loser&apos; or &apos;winner&apos; during a merge</description>
    <label>Winner or Loser</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Loser</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WinnerIdTaggingForDeDupe.cls
public class WinnerIdTaggingForDeDupe {
    
    public static void setWinnerIds(){
        
        List<DeDupe_Record_Back_Up__c> allWinnerRecords = [SELECT Id,Original_Record_Id__c, De_Dupe_Key_Value__c,Winner_ID__c 
                                                           FROM DeDupe_Record_Back_Up__c
                                                           WHERE Winner_or_Loser__c = 'Winner'];
        
        List<DeDupe_Record_Back_Up__c> allLoserRecords = [SELECT Id, Original_Record_Id__c, De_Dupe_Key_Value__c,Winner_ID__c 
                                                          FROM DeDupe_Record_Back_Up__c
                                                          WHERE Winner_or_Loser__c = 'Loser'];
        
        Map<String,String> DeDupeValueKeyTowinnerOrginalId = new Map<String,String>();
        
        List<DeDupe_Record_Back_Up__c> losersToUpdate = new List<DeDupe_Record_Back_Up__c>();
        
        for(DeDupe_Record_Back_Up__c winner : allWinnerRecords){
            String keyValue = winner.De_Dupe_Key_Value__c;
            DeDupeValueKeyTowinnerOrginalId.put(keyValue.toLowerCase(), winner.Original_Record_Id__c);
        }
        
        for(DeDupe_Record_Back_Up__c loser : allLoserRecords){
            String keyValue = loser.De_Dupe_Key_Value__c;
            loser.Winner_ID__c = DeDupeValueKeyTowinnerOrginalId.get(keyValue.toLowerCase());
            losersToUpdate.add(loser);
        }
        
        if(!losersToUpdate.isEmpty()){
            update losersToUpdate;
        }
        
    }
    
    
}